trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

workspace:
  clean: all

strategy:
  matrix:
    Electron2:
      RuntimeURL: https://atom.io/download/atom-shell
      RuntimeName: iojs
      RuntimeVersion: v5.0.4

pool:
  vmImage: 'vs2017-win2016'

variables:
  SLBuildDirectory: build
  SLGenerator: Visual Studio 15 2017 Win64
  SLDistributeDirectory: distribute
  FullDistributePath: $(SLBuildDirectory)\$(SLDistributeDirectory)
  DistributionAritfact: $(RuntimeName)-$(RuntimeVersion)-crash-handler

steps:
- powershell: git config --global core.autocrlf false
  displayName: 'Set Unix checkout for git'

- checkout: self
  fetchDepth: 10

- task: NodeTool@0
  displayName: 'Install Node'
  inputs:
    versionSpec: '10.x'

- script: 'yarn install'
  displayName: 'Install dependencies'

- script: 'cmake -H. -B"%SLBuildDirectory%" -G"%SLGenerator%"  -DCMAKE_INSTALL_PREFIX="%FullDistributePath%\crash-handler" -DNODEJS_NAME=%RuntimeName% -DNODEJS_URL=%RuntimeURL% -DNODEJS_VERSION=%RuntimeVersion%'
  displayName: 'Configure crash-handler'

- script: 'cmake --build %SLBuildDirectory% --target install --config RelWithDebInfo'
  displayName: 'Build crash-handler'

- task: ArchiveFiles@2
  displayName: 'Generate artifact'
  inputs:
    rootFolderOrFile: $(FullDistributePath)\crash-handler
    includeRootFolder: true
    archiveType: tar
    tarCompression: gz
    archiveFile: '$(DistributionAritfact).tar.gz'

- task: GithubRelease@0 
  displayName: 'Deploy to GitHub'
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))  
  inputs:
    gitHubConnection: stream-labs_deploy
    repositoryName: stream-labs/crash-handler
    assets: $(Build.SourcesDirectory)/$(DistributionAritfact).tar.gz