trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

workspace:
  clean: all

strategy:
  matrix:
    Electron2:
      RuntimeURL: https://atom.io/download/atom-shell
      RuntimeName: iojs
      RuntimeVersion: v5.0.4

pool:
  vmImage: 'vs2017-win2016'

variables:
  SLBuildDirectory: build
  SLGenerator: Visual Studio 15 2017 Win64
  SLDistributeDirectory: distribute
  FullDistributePath: $(SLBuildDirectory)\$(SLDistributeDirectory)
  DistributionAritfact: $(RuntimeName)-$(RuntimeVersion)-crash-handler

steps:
- powershell: git config --global core.autocrlf false
  displayName: 'Set Unix checkout for git'

- checkout: self
  fetchDepth: 10

- task: NodeTool@0
  displayName: 'Install Node'
  inputs:
    versionSpec: '10.x'

- script: 'yarn install'
  displayName: 'Install dependencies'

- script: 'cmake -H. -B"%SLBuildDirectory%" -G"%SLGenerator%"  -DCMAKE_INSTALL_PREFIX="%FullDistributePath%\crash-handler" -DNODEJS_NAME=%RuntimeName% -DNODEJS_URL=%RuntimeURL% -DNODEJS_VERSION=%RuntimeVersion%'
  displayName: 'Configure crash-handler'

- script: 'cmake --build %SLBuildDirectory% --target install --config RelWithDebInfo'
  displayName: 'Build crash-handler'

- script: |
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-file-l1-2-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-file-l2-1-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-localization-l1-2-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-processthreads-l1-1-1.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-synch-l1-2-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-timezone-l1-1-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-convert-l1-1-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-heap-l1-1-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-multibyte-l1-1-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-runtime-l1-1-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-stdio-l1-1-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-string-l1-1-0.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
    copy "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Redist\MSVC\14.16.27012\x64\Microsoft.VC141.CRT\vcruntime140.dll" "%SLFullDistributePath%\obs-studio-node\"
    copy "C:\Program Files (x86)\Microsoft Visual Studio\Installer\ucrtbase.dll" "$(FullDistributePath)\crash-handler\crash-handler\"
  displayName: 'Copy necessary dll files'

- task: ArchiveFiles@2
  displayName: 'Generate artifact'
  inputs:
    rootFolderOrFile: $(FullDistributePath)\crash-handler\crash-handler
    includeRootFolder: true
    archiveType: tar
    tarCompression: gz
    archiveFile: '$(DistributionAritfact).tar.gz'

- task: GithubRelease@0 
  displayName: 'Deploy to GitHub'
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))  
  inputs:
    gitHubConnection: stream-labs_deploy
    repositoryName: stream-labs/crash-handler
    assets: $(Build.SourcesDirectory)/$(DistributionAritfact).tar.gz